plugins {
    id 'com.android.application'
}

android {
    namespace '__PACKAGE_NAME__'
    compileSdk __COMPILE_SDK__

    defaultConfig {
        applicationId '__PACKAGE_NAME__'
        minSdk __MIN_SDK__
        targetSdk __TARGET_SDK__
        versionCode __VERSION_CODE__
        versionName '__VERSION_NAME__'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
}
